#!/bin/bash
declare -A exe
#copy the following lines to a file "local" to change executables for various schemes
################################################################################
export TINYSCHEMEINIT=/usr/share/tinyscheme/init.scm
exe=(
	[chicken]="csi -s" 
	[chibi]="chibi"
	[guile]="guile --no-auto-compile"
	[sig]="./arguments sscm" # sscm is the executable, ./arguments is shim
	[tiny]="./arguments tinyscheme" # tinyscheme is the executable, ./arguments is shim
	[mit]="./mit mit-scheme" # mit-scheme is the executable, ./mit is shim
)
################################################################################
[[ -f local ]] && source local

#all="chibi chicken guile mit tiny"
all=${!exe[@]}
all=$(echo $all|tr ' ' '\n'|shuf) #shuffle all
case "$1" in
	   chibi | b )  ${exe[chibi]}  "${@:2}" ;;
	 chicken | n ) ${exe[chicken]} "${@:2}" ;;
	   guile | g )  ${exe[guile]}  "${@:2}" ;;
	     mit | m )   ${exe[mit]}   "${@:2}" ;;
	     sig | s )   ${exe[sig]}   "${@:2}" ;;
	    tiny | t )  ${exe[tiny]}   "${@:2}" ;;
	all | "" | a ) 
		for f in $all ; do 
			echo ";;;;$f;;;;" ; ${exe[$f]} "${@:2}" ; 
		done ;;
	* ) echo "idiot" ;; 
esac
