#!/bin/bash
declare -A exe

#copy the following lines to a file "local" to change executables for various schemes
################################################################################
exe=(
	[chicken]="csi -s" 
	[chibi]="chibi"
	[guile]="guile --no-auto-compile"
	[tiny]="./tiny"
	[mit]="mit-scheme"
)
export TINYSCHEMEINIT=/usr/share/tinyscheme/init.scm
################################################################################

[[ -f local ]] && source local

case "$1" in
	chibi   | b ) ${exe[chibi]} "${@:2}" ;;
	chicken | n ) ${exe[chicken]} "${@:2}" ;;
	guile   | g ) ${exe[guile]} "${@:2}" ;;
	tiny    | t ) ${exe[tiny]} "${@:2}" ;;
	all     | a ) 
		for f in chibi chicken guile tiny ; do 
			echo "   $f   " ; ${exe[$f]} "${@:2}" ; done ;;
	* ) echo "idiot" ;; 
esac
